services:
  meetny-frontend:
    build: ./frontend
    container_name: meetny-frontend
    expose:
      - "3001"
    networks:
      - npm-net
    restart: unless-stopped

networks:
  npm-net:
    external: true
